# Generated by Django 2.1.7 on 2019-05-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190507_1835'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='nyteuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='nyteuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='nyteuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
