# Generated by Django 2.1.7 on 2019-05-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190526_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='protomenuitem',
            name='item_type',
            field=models.CharField(choices=[('sp', 'Special'), ('be', 'Beer'), ('wi', 'Wine'), ('co', 'Cocktail'), ('so', 'Soda')], default='be', max_length=100),
        ),
    ]
