# Generated by Django 2.1.7 on 2019-05-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190526_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='protoorder',
            name='message_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='protomenuitem',
            name='item_type',
            field=models.CharField(choices=[('sp', 'Special'), ('be', 'Beer'), ('wi', 'Wine'), ('co', 'Cocktail'), ('so', 'Soda'), ('li', 'Liquor')], default='be', max_length=100),
        ),
    ]
