# Generated by Django 2.1.7 on 2019-05-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190528_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='nyteuser',
            name='facebook_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nyteuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='nyteuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='middle name'),
        ),
        migrations.AddField(
            model_name='nyteuser',
            name='phone',
            field=models.CharField(max_length=64, null=True, verbose_name='user phone'),
        ),
        migrations.AddField(
            model_name='nyteuser',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='nyteuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='nyteuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
    ]
