# Generated by Django 2.1.7 on 2019-05-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190529_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyteuser',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='nyteuser',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='last name'),
        ),
    ]
