# Generated by Django 2.1.7 on 2019-06-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190529_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyteuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='nyteuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='nyteuser',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nyteuser',
            name='user_type',
            field=models.CharField(choices=[('PA', 'Patron'), ('OW', 'Owner'), ('BA', 'Bartender')], default='PA', max_length=100, null=True),
        ),
    ]
