# Generated by Django 2.1.7 on 2019-06-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190603_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='nyteuser',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
