# Generated by Django 2.1.7 on 2019-06-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='attempted_to_verify',
            field=models.BooleanField(default=False),
        ),
    ]
