# Generated by Django 2.1.7 on 2019-06-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_verification_attempted_to_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='dob',
        ),
        migrations.AddField(
            model_name='verification',
            name='dob_day',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='verification',
            name='dob_month',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='verification',
            name='dob_year',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='verification',
            name='error_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='verification',
            name='error_msg',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='verification',
            name='addr',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='verification',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='verification',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='verification',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='verification',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='verification',
            name='uuid',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='verification',
            name='zipcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
