# Generated by Django 2.1.7 on 2019-06-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190606_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nyteuser',
            name='birthday',
        ),
        migrations.AddField(
            model_name='nyteuser',
            name='dob_day',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nyteuser',
            name='dob_month',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nyteuser',
            name='dob_year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
