# Generated by Django 2.1.7 on 2019-06-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190606_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='status',
            new_name='verif_status',
        ),
        migrations.AddField(
            model_name='verification',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
