# Generated by Django 2.1.7 on 2019-06-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190607_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='verif_email',
            new_name='email',
        ),
    ]
