# Generated by Django 2.1.7 on 2019-06-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190607_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='nyteuser',
            name='id_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='verification',
            name='image_data',
            field=models.TextField(default=''),
        ),
    ]
