# Generated by Django 2.1.7 on 2019-06-09 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190609_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='image_data',
        ),
        migrations.AddField(
            model_name='verificationid',
            name='verification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Verification'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationid',
            name='image',
            field=models.ImageField(upload_to='staticfiles/id_images/'),
        ),
    ]
