# Generated by Django 2.1.7 on 2019-06-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190609_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='image',
            field=models.ImageField(null=True, upload_to='staticfiles/id_images/'),
        ),
    ]
