# Generated by Django 2.1.7 on 2019-06-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_verification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='stripe_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
