# Generated by Django 2.1.7 on 2019-06-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190617_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='nyteuser',
            name='stripe_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
