# Generated by Django 2.1.7 on 2019-06-28 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_nyteuser_stripe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=100)),
                ('payment_source', models.CharField(blank=True, max_length=100)),
                ('amount', models.FloatField()),
                ('paid', models.BooleanField(blank=True, default=False)),
                ('failure_code', models.CharField(blank=True, max_length=50)),
                ('failure_message', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='nyteuser',
            name='account_balance',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='nyteuser',
            name='default_payment',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
