# Generated by Django 2.1.7 on 2019-06-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190628_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyteuser',
            name='membership',
            field=models.ManyToManyField(blank=True, to='api.WorksAt'),
        ),
        migrations.AlterField(
            model_name='nyteuser',
            name='stripe_id',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reload',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
