# Generated by Django 2.1.7 on 2019-06-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190628_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reload',
            name='failure_code',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reload',
            name='failure_message',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reload',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
