# Generated by Django 2.1.7 on 2019-06-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20190628_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='reload',
            name='has_attempted_to_reload',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
