# Generated by Django 2.1.7 on 2019-06-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20190629_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='data',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='eta',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancal_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='canceled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_total',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='placed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ready',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
