# Generated by Django 2.1.7 on 2019-06-29 23:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20190629_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
