# Generated by Django 2.1.7 on 2019-06-29 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20190629_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='placed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 29, 23, 52, 39, 682561), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, default='submitted', max_length=100),
        ),
    ]
