# Generated by Django 2.1.7 on 2019-07-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20190630_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyteuser',
            name='account_balance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reload',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
