# Generated by Django 2.2.3 on 2019-07-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_transaction_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cancal_reason',
            new_name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='convenience_fee',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='convenience_fee',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='sales_tax',
            field=models.FloatField(blank=True, default=6.0, null=True),
        ),
    ]
