# Generated by Django 2.1.7 on 2019-07-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20190711_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_data_formatted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
