# Generated by Django 2.2.3 on 2019-07-24 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_menuoption_optionvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionvalue',
            name='option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.MenuOption'),
        ),
        migrations.CreateModel(
            name='OptionValuePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MenuOption')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Transaction')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OptionValue')),
            ],
        ),
    ]
