# Generated by Django 2.2.3 on 2019-07-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20190725_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuoption',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.Category'),
        ),
    ]
