# Generated by Django 2.2.3 on 2019-07-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20190727_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuoption',
            old_name='category',
            new_name='menu_item',
        ),
    ]
