# Generated by Django 2.2.3 on 2019-07-29 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20190729_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuoption',
            name='menu_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.MenuItem'),
        ),
    ]
