# Generated by Django 2.2.3 on 2019-07-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20190729_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='reload',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
