# Generated by Django 2.2.3 on 2019-08-10 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_reload_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionvalue',
            name='option',
        ),
    ]
