# Generated by Django 2.2.3 on 2019-08-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_optionvalue_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuoption',
            name='menu_item',
        ),
        migrations.CreateModel(
            name='OptionPairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MenuItem')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='api.MenuOption')),
            ],
        ),
    ]
