# Generated by Django 2.2.3 on 2019-08-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20190810_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionpairing',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.MenuItem'),
        ),
        migrations.AlterField(
            model_name='optionpairing',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MenuOption'),
        ),
    ]
