# Generated by Django 2.2.3 on 2019-08-12 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20190810_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionpairing',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='api.MenuItem'),
        ),
    ]
