# Generated by Django 2.2.3 on 2019-08-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_transaction_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalue',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
