# Generated by Django 2.2.3 on 2019-08-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20190813_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total',
        ),
        migrations.AddField(
            model_name='transaction',
            name='subtotal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tip',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
