# Generated by Django 2.2.3 on 2019-08-14 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0004_auto_20181128_1642'),
        ('api', '0065_auto_20190813_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcm_django.FCMDevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
