# Generated by Django 2.2.3 on 2019-08-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_patrondevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='fcm_token',
            field=models.CharField(default='', max_length=250),
        ),
    ]
