# Generated by Django 2.2.3 on 2019-08-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_verification_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='fcm_token',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
