# Generated by Django 2.2.3 on 2019-08-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_transaction_notification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='notification_status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='canceled_notif_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='completed_notif_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='in_progress_notif_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
