# Generated by Django 2.2.3 on 2019-08-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20190822_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card_details',
            field=models.CharField(default='', max_length=50),
        ),
    ]
