# Generated by Django 2.2.3 on 2019-08-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20190827_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='nyteuser',
            name='id_image',
            field=models.ImageField(default='None', null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='venues/'),
        ),
    ]
