# Generated by Django 2.2.3 on 2019-08-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20190828_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='crowd_size',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='price_level',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='tagline',
        ),
        migrations.AddField(
            model_name='venue',
            name='minimum_age',
            field=models.IntegerField(blank=True, default=21),
        ),
    ]
