# Generated by Django 2.2.3 on 2019-08-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20190828_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_images/')),
                ('name', models.CharField(max_length=200)),
                ('descr', models.CharField(max_length=200)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Venue')),
            ],
        ),
    ]
