# Generated by Django 2.1.7 on 2019-09-25 02:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_venueimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='hours_of_operation',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='image',
            field=models.ImageField(null=True, upload_to='users/'),
        ),
    ]
